### ISSUE TITLE
Azure automation: Import module failed

### ISSUE THREAD

**Issue by O365KY** [SpanningCloudApps/SB365-Powershell#14]
Getting the following failure when trying to import: 
Error importing the module SpanningO365. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred during module validation. When importing the module to an internal PowerShell session, it was not able to be loaded by PowerShell. There is likely an issue with the contents of the module that results in PowerShell's not being able to load it. Please verify that the module imports successfully in a local PowerShell session, correct any issues, and then try importing again.

**Comment by SPMatthewMcD** [comment]
Did you pull that from the Releases page? That release is set up for Azure. I still have to change the project over so that they match.

**Comment by O365KY** [comment]
https://spanning.com/blog/spanning-backup-for-office-365-powershell-module-update-3401/?utm_source=feedburner&utm_medium=twitter&utm_campaign=Feed%3A+spanningbackupnews+%28Spanning+Backup+Blog%29

I got it imported using version 3.3.0.0.  However, following your video, I still can’t get pass this failed error.  I can’t figure it out.  Thanks.

Travis

clear-spanningauthentication
$auth- Get-SpanningAuthentication -connection $(Get-AutomationConnection -Name 'Spanning') -verbose
get-spanningadmins -authinfo $auth

Failed
At line:2 char:7
+ $auth- Get-SpanningAuthentication -connection $(Get-AutomationConnect ...
+       ~
You must provide a value expression following the '-' operator.

At line:2 char:8
+ $auth- Get-SpanningAuthentication -connection $(Get-AutomationConnect ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'Get-SpanningAuthentication' in expression or statement.



Travis Hayes
Server Architect, Technology Services
MCP, MCSA Server 2012 & MCSA Office 365
Administrative Office of the Courts
1001 Vandalay Dr. Frankfort, KY40601
502-573-2350 x50155
travishayes@kycourts.net<mailto:travishayes@kycourts.net>
[mcsa-office-365-certified-2018][mcsa-windows-server-2012-certified-2016]

**Comment by SPMatthewMcD** [comment]
You have a typo.

$auth-
________________________________

**Comment by O365KY** [comment]
Thanks for the response.  Unfortunately for me, I’m still getting the same error.  No worries.  I was just trying to learn something new.
clear-spanningauthentication
$auth - Get-SpanningAuthentication -connection $(Get-AutomationConnection -Name 'Spanning') -verbose
get-spanningadmins -authinfo $auth


Failed

At line:2 char:8

+ $auth - Get-SpanningAuthentication -connection $(Get-AutomationConnec ...

+        ~

You must provide a value expression following the '-' operator.



At line:2 char:9

+ $auth - Get-SpanningAuthentication -connection $(Get-AutomationConnec ...

+         ~~~~~~~~~~~~~~~~~~~~~~~~~~

Unexpected token 'Get-SpanningAuthentication' in expression or statement.

Travis Hayes
Server Architect, Technology Services
MCP, MCSA Server 2012 & MCSA Office 365
Administrative Office of the Courts
1001 Vandalay Dr. Frankfort, KY40601
502-573-2350 x50155
travishayes@kycourts.net<mailto:travishayes@kycourts.net>
[mcsa-office-365-certified-2018][mcsa-windows-server-2012-certified-2016]

**Comment by SPMatthewMcD** [comment]
Change your code to this:
```
clear-spanningauthentication
$auth = Get-SpanningAuthentication -connection $(Get-AutomationConnection -Name 'Spanning') -verbose
get-spanningadmins -authinfo $auth
```

The `$auth-` should be `$auth=`

**Comment by O365KY** [comment]
Got it.  Thanks!

Travis Hayes
Server Architect, Technology Services
MCP, MCSA Server 2012 & MCSA Office 365
Administrative Office of the Courts
1001 Vandalay Dr. Frankfort, KY40601
502-573-2350 x50155
travishayes@kycourts.net<mailto:travishayes@kycourts.net>
[mcsa-office-365-certified-2018][mcsa-windows-server-2012-certified-2016]
