### ISSUE TITLE
Global Admin - UnathorizedError

### ISSUE THREAD

**Issue by audioeptesicus** [SpanningCloudApps/SB365-Powershell#20]
```
PS C:\>$Auth = Get-SpanningAuthentication -ApiToken "xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -Region "US" -AdminEmail "SpanningServiceAccount@xxxxxxxx.onmicrosoft.com"
PS C:\>Get-SpanningAdmins -AuthInfo $Auth
Invoke-WebRequest : {"code":"UnauthorizedError","message":""}
At C:\SB365-Powershell-master\SpanningO365\Private\Invoke-SpanningRequest.ps1:97 char:23
+ ... $response = Invoke-WebRequest -uri $request -Headers $headers -Method ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Invoke-WebRequest : Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\SB365-Powershell-master\SpanningO365\Private\Invoke-SpanningRequest.ps1:100 char:50
+ ...         $response = Invoke-WebRequest -uri $response.nextLink -Header ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-WebRequest], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

We recently created a global admin account (seen here as SpanningServiceAccount), which is seen in our Spanning portal and also shows up running Get-SpanningAdmins using another account. No commands using this service account work and result in the error above.

When running the command below by itself, it shows that it's authorized, but I cannot successfully execute any commands using the account. I've even ran Clear-SpanningAuthorization, but that doesn't resolve the issue.
`Get-SpanningAuthentication -ApiToken "xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -Region "US" -AdminEmail "SpanningServiceAccount@xxxxxxxx.onmicrosoft.com"`

The file and line from the error in question is here (Character 23 starts at "Request" in Invoke-WebRequest):
`$response = Invoke-WebRequest -uri $request -Headers $headers -Method GET -UseBasicParsing | ConvertFrom-Json`

**Comment by SPMatthewMcD** [comment]
When you generated the token used in the API request, did you generate it with the account SpanningServiceAccount@@xxxxxxxx.onmicrosoft.com? Each admin account has to be used with the unique token created for that account.

**Comment by audioeptesicus** [comment]
No. 😒 That makes way more sense. I must've missed it in the documentation about that. I'll certainly try that tomorrow. Thank you!

**Comment by SPMatthewMcD** [comment]
Please let me know what happens. I'll have a look in the documentation and make sure I clarify it. (If we're right, you aren't the first to get caught by this.) It this is not the solution, please raise a ticket with support@spanning.com and I can look into your accounts. Include in the ticket that you have been working with me.

**Comment by audioeptesicus** [comment]
That's definitely what it was. Thanks for the help! I was disappointed to hear that Spanning support will not support this powershell integration, even though we were sold on this being a piece of the solution. They would not assist in this at all and directed me here.

**Comment by SPMatthewMcD** [comment]
I'll talk to them. The module is my baby. So I can support it most easily here. They should have directed the ticket to me internally. With regards to the documentation, do you think I should clarify the account specific GUID in the Authentication section here: https://github.com/SpanningCloudApps/SB365-Powershell#authentication ?
