### ISSUE TITLE
UnauthorizedError - InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest)

### ISSUE THREAD

**Issue by dubmachine** [SpanningCloudApps/SB365-Powershell#21]
Hopefully a simple one but when running the following PS command I get the error below

**Get-SpanningAuthentication -ApiToken XXXXXXXXXXXXXXXXXXXX -Region
 EU -AdminEmail XXXXXX@XXXXX.com | Get-SpanningTenantInfo**

```
> Invoke-WebRequest : {"code":"UnauthorizedError","message":""}
> At C:\tmp\PowerShell\SB365-Powershell\spanningo365\Private\Invoke-SpanningRequest.ps1:136 char:20
> + ...  $results = Invoke-WebRequest -uri $request -Headers $headers -Method ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
>    eption
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

If I run the command without **| Get-SpanningTenantInfo** I receive the following so I don't think it's authentication related. 

```
> Headers         Region
> -------         ------
> {Authorization} EU
```

Thanks

J

**Comment by SPMatthewMcD** [comment]
This is usually caused by using a poorly formed token or the wrong email account. The admin email parameter has to be the same as the one that generated the token. If you double check your code and it still does not work send me an email at matt.mcdermott@spanning.com so I can check your tenant.

**Comment by dubmachine** [comment]
Thanks Matt, solved the problem, I knew it would simple! I have two difference email aliases and it was using the wrong one. (facepalm)

**Comment by SPMatthewMcD** [comment]
Glad you sorted it out. Let me know if there is anything else. I published a bunch of samples here : https://github.com/SpanningCloudApps/SB365-Powershell/blob/master/samples.md and a detailed one here https://github.com/SpanningCloudApps/SB365-Powershell/blob/master/sample-license-users.md
