### ISSUE TITLE
build v3.4.0.2 with error "underlying connection was closed: an unexpected error occured on a send"

### ISSUE THREAD

**Issue by calvinlee02072** [SpanningCloudApps/SB365-Powershell#22]
build v3.4.0.2 with error "underlying connection was closed: an unexpected error occured on a send"

**Comment by calvinlee02072** [comment]
PS D:\SB365\SpanningO365-v3.4.0.2-full\SpanningO365\3.4.0.2> Get-SpanningAdmins
Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.
At D:\SB365\SpanningO365-v3.4.0.2-full\SpanningO365\3.4.0.2\Private\Invoke-SpanningRequest.ps1:97 char:23
+ ... $response = Invoke-WebRequest -uri $request -Headers $headers -Method ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Invoke-WebRequest : Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At D:\SB365\SpanningO365-v3.4.0.2-full\SpanningO365\3.4.0.2\Private\Invoke-SpanningRequest.ps1:100 char:50
+ ...         $response = Invoke-WebRequest -uri $response.nextLink -Header ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-WebRequest], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by SPMatthewMcD** [comment]
Hi @calvinlee02072, Can you provide some background on what you are trying to do, what PowerShell command did you try. I cannot take action on the error message alone.

**Comment by calvinlee02072** [comment]
Hello Matthew,

Thanks for your reply.  I had been utilizing the SB365 Powershell module to
get the active Spanning users to compare with a Grouper group to see if any
Grouper group member is not an active Spanning user.



get-spanningassignedusers |select userPrincipalName,assigned,isdeleted
|export-csv -path "z:\Law_Spanning\Spanning_active_users.csv"
-NoTypeInformation

**Comment by SPMatthewMcD** [comment]
How are you getting authenticated? If you want you can send me the details in email at matt.mcdermott@spanning.com or post the auth info without your real Auth token. Generally I find these errors are related to incorrect authentication.

**Comment by SPMatthewMcD** [comment]
Spoke with Calvin separately and determined this was a network issue with the firewall or VPN or both.
