### ISSUE TITLE
Disable-SpanningUser doesn't work.

### ISSUE THREAD

**Issue by hemingsent** [SpanningCloudApps/SB365-Powershell#29]
When using Disable-SpanningUser a license is never removed.  I have also tried Disable-SpanningUsersFromCSVAdvanced and the same thing happens. I can share output if you would like.

I revoked my API key and tried another generated one but the same issue persists.

**Comment by hemingsent** [comment]
Just saw there was a new release, I will try to read first next time :D .

**Comment by MatthewMcD** [comment]
If it isn’t working in this latest release please let me know. I have another release coming on Tuesday for the new bulk endpoint that we’d prefer you use for licenses.

Either way let me know and I’ll help out!

Matthew

Pardon the typos, sent from my mobile phone.
________________________________

**Comment by hemingsent** [comment]
This was my fault. I was using the old version of SB365 without realizing Disable-SpanningUsersFromCSVAdvanced was deprecated. After I updated the module all is working.
Thanks!
