### ISSUE TITLE
API Errors

### ISSUE THREAD

**Issue by MZalusky** [SpanningCloudApps/SB365-Powershell#35]
We have been using the API successfully for quite a while but have been receiving the following error when trying to get license information the past few days:

Invoke-WebRequest : Cannot GET /tenant
At C:\Spanning365\SpanningO365\Private\Invoke-SpanningRequest.ps1:136 char:20
+ ...  $results = Invoke-WebRequest -uri $request -Headers $headers -Method ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by SPMatthewMcD** [comment]
Have you updated to the latest module? We updated the API and endpoint address to enhance the capacity and add new features. The updated module should work for you.

**Comment by MZalusky** [comment]
Thanks, I had tried that but I guess I didn't fully disconnect and reconnect so it was still giving me the errors. I just tried again from a fresh session and it went through successfully.

Thank you, sorry for the troubles,

Mike

Mike Zalusky
Service Manager
201.796.0404
[logo]<https://www.baroan.com/>


From: Matthew McDermott ***@***.***>
Sent: Tuesday, April 20, 2021 2:04 PM
To: SpanningCloudApps/SB365-Powershell ***@***.***>
Cc: Michael Zalusky ***@***.***>; Author ***@***.***>
Subject: [E] Re: [SpanningCloudApps/SB365-Powershell] API Errors (#35)


Have you updated to the latest module? We updated the API and endpoint address to enhance the capacity and add new features. The updated module should work for you.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSpanningCloudApps%2FSB365-Powershell%2Fissues%2F35%23issuecomment-823488930&data=04%7C01%7Cmzalusky%40baroan.com%7C16e76fa22c91448fdf9708d90426c216%7C16a61d71c73f485998f7632eca112b70%7C1%7C0%7C637545386817532702%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3Jvsogjq5LdA4FpYwjlSKlo%2Bzsj%2FRUH60afhSLutdpg%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATYPL4INGXWAD2NEKYT4LMLTJW623ANCNFSM43ITCZQA&data=04%7C01%7Cmzalusky%40baroan.com%7C16e76fa22c91448fdf9708d90426c216%7C16a61d71c73f485998f7632eca112b70%7C1%7C0%7C637545386817542654%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1UMR%2FnFFWXXAxDO%2Bywiaz6uqH6rYy6k20PbadUORpfY%3D&reserved=0>.

________________________________

PLEASE NOTE: To expedite your service requests, the following is recommended:

Please open a support ticket by sending an email to ***@***.***, logging into the Baroan Technologies portal or calling our office at 201-796-0404 during business hours. Normal business hours are Monday through Friday from 8 AM to 5 PM.

If assistance is required after business hours, your company must have an AFTER HOURS Support Agreement in place. A separate phone number is provided to authorized companies. Please do not leave messages on the regular office phone number for AFTER HOURS requests as they will not be received until the following business morning.

Please note that AFTER HOURS support is for EMERGENCIES ONLY.

**Comment by SPMatthewMcD** [comment]
No worries, happy its working. I'll close with this comment, but if you hit any snags I'll be here to help.
