### ISSUE TITLE
Invoke-WebRequest : Too many requests

### ISSUE THREAD

**Issue by TRipka07** [SpanningCloudApps/SB365-Powershell#40]
Hello,

We have a PowerShell script to license Spanning users who are members of an AD group and are experiencing this error when the script runs.

TerminatingError(Invoke-WebRequest): "Too many requests, please try again later."
Invoke-WebRequest : Too many requests, please try again later.

How can we resolve this?

Thanks,
Tanner

**Comment by SPMatthewMcD** [comment]
Can you try the sample here: https://github.com/SpanningCloudApps/SB365-Powershell/blob/master/samples.md#license-an-azure-ad-group We have a new "bulk" endpoint that enables up to 500 users in one request.

**Comment by SPMatthewMcD** [comment]
It looks like your user list has more than 500 items.

The bulk API accepts up to 500 users per request.

Can you try grouping them into 500 item lots? Something like this:
#Break List into batches of 500
    $group = 500
    $i = 0
    $userBatch = @()
    $results = @()
    do {
        #Send the batch of Users 500 at a time.
        $userBatch = $userList[$i..(($i+= $group) - 1)]
        if ($pscmdlet.ShouldProcess("Processing $($userBatch.Count) users", "Enable-SpanningUserList")){
            $resultsBatch = Enable-SpanningUserList -AuthInfo $AuthInfo -UserPrincipalNames $userBatch

            #Need to join the results
            $results += $resultsBatch
        }
    }
    until ($i -gt $userList.count -1)

________________________________

**Comment by SPMatthewMcD** [comment]
Can you try grouping them into 500 item lots? Something like this:
```powershell
#Break List into batches of 500
    $group = 500
    $i = 0
    $userBatch = @()
    $results = @()
    do {
        #Send the batch of Users 500 at a time.
        $userBatch = $userList[$i..(($i+= $group) - 1)]
        if ($pscmdlet.ShouldProcess("Processing $($userBatch.Count) users", "Enable-SpanningUserList")){
            $resultsBatch = Enable-SpanningUserList -AuthInfo $AuthInfo -UserPrincipalNames $userBatch

            #Need to join the results
            $results += $resultsBatch
        }
    }
    until ($i -gt $userList.count -1)
```

**Comment by TRipka07** [comment]
I've added the batch suggestion and I'm receiving this error.

Enable-SpanningUserList : Cannot validate argument on parameter 'UserPrincipalNames'. The number of provided arguments, (1297), exceeds the maximum number of allowed arguments 
(500). Provide fewer than 500 arguments, and then try the command again.
At C:\Scripts\SpanningBackup\Enable-SpanningUser_v2.ps1:44 char:45
+ Enable-SpanningUserList -UserPrincipalNames $userList
+                                             ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Enable-SpanningUserList], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Enable-SpanningUserList



Here is the script with the batch inserted and I may something out of order. Sorry, my powershell skills are not the best.

`#Connect to Spanning
Get-SpanningAuthentication -ApiToken $Password -Region US -AdminEmail spanningadmin@domain.com

#Assign licenses to users
#Create an ArrayList
$userList = [System.Collections.ArrayList]@()

#Break List into batches of 500
    $group = 500
    $i = 0
    $userBatch = @()
    $results = @()
    do {
        #Send the batch of Users 500 at a time.
        $userBatch = $userList[$i..(($i+= $group) - 1)]
        if ($pscmdlet.ShouldProcess("Processing $($userBatch.Count) users", "Enable-SpanningUserList")){
            $resultsBatch = Enable-SpanningUserList -AuthInfo $AuthInfo -UserPrincipalNames $userBatch

            #Need to join the results
            $results += $resultsBatch
        }
    }
    until ($i -gt $userList.count -1)

Get-ADGroupMember -Identity "Spanning Backup Users" | Get-ADUser -Properties userPrincipalName | `
foreach {$userList.Add($_.UserPrincipalName)}
#Submit the list to Spanning
Enable-SpanningUserList -UserPrincipalNames $userList
`

**Comment by SPMatthewMcD** [comment]
Are you certain your array has fewer than 500 items? The error indicates that you are still passing too much data.

**Comment by SPMatthewMcD** [comment]
Please email me at matt.mcdermott@spanning.com. If you are available between 12-2 central tomorrow we can do a quick screen sharing session and I can help you with your script.

**Comment by SPMatthewMcD** [comment]
I am going to write up a sample for this. Closing for now.
