### ISSUE TITLE
Spanning PS Get Users Command:  Not Working

### ISSUE THREAD

**Issue by CRSMDGuy** [SpanningCloudApps/SB365-Powershell#42]
I use to run the following command to export a list of all assigned users,  Its no longer working.

Here is the command that use to work with out issues:

Get-SpanningAssignedUsers -size 10000 | Export-CSV .\assigned.csv 

Please help.  See attached screenshot,
![Get Users Command Not Working](https://user-images.githubusercontent.com/87444857/125675826-6ffa1705-77f6-4e8c-9de1-404a9b5db994.PNG)

**Comment by CRSMDGuy** [comment]
Here is the command that use to work with out issues:

Get-SpanningAssignedUsers -size 10000 | Export-CSV .\assigned.csv

**Comment by SPMatthewMcD** [comment]
Thanks for the issue. The size parameter has a max of 1000. You may be bumping into the 504 error that we are tracking on #41 I am going to close this and track the 504 issue on 41.

**Comment by CRSMDGuy** [comment]
Matt

Thanks for following up.

Regards,

Mike Cantow

***@***.***D77ED8.C4200EF0]
