### ISSUE TITLE
Get-SpanningAdmins - not working Invoke-WebRequest : Cannot GET /users?size=1000

### ISSUE THREAD

**Issue by MGrnovic** [SpanningCloudApps/SB365-Powershell#43]
HI --

Any help with the error below would be appreciated.

Thank you

PS C:\Utils\Spanning\SpanningO365\3.5.0.0> Get-Command -Module SpanningO365

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Clear-SpanningAuthentication                       3.5.0.0    SpanningO365
Function        Disable-SpanningUser                               3.5.0.0    SpanningO365
Function        Disable-SpanningUserList                           3.5.0.0    SpanningO365
Function        Disable-SpanningUsersFromCSVAdvanced               3.5.0.0    SpanningO365
Function        Enable-SpanningUser                                3.5.0.0    SpanningO365
Function        Enable-SpanningUserList                            3.5.0.0    SpanningO365
Function        Enable-SpanningUsersFromCSVAdvanced                3.5.0.0    SpanningO365
Function        Get-SpanningAdmins                                 3.5.0.0    SpanningO365
Function        Get-SpanningAssignedUsers                          3.5.0.0    SpanningO365
Function        Get-SpanningAuthentication                         3.5.0.0    SpanningO365
Function        Get-SpanningNonAdmins                              3.5.0.0    SpanningO365
Function        Get-SpanningTenantInfo                             3.5.0.0    SpanningO365
Function        Get-SpanningTenantInfoPaymentStatus                3.5.0.0    SpanningO365
Function        Get-SpanningUnassignedUsers                        3.5.0.0    SpanningO365
Function        Get-SpanningUser                                   3.5.0.0    SpanningO365
Function        Get-SpanningUsers                                  3.5.0.0    SpanningO365

PS C:\Utils\Spanning\SpanningO365\3.5.0.0> Get-SpanningAdmins
Invoke-WebRequest : Cannot GET /users?size=1000
At C:\Utils\Spanning\SpanningO365\3.5.0.0\Private\Invoke-SpanningRequest.ps1:105 char:23
+ ... $response = Invoke-WebRequest -uri $request -Headers $headers -Method ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Invoke-WebRequest : Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\Utils\Spanning\SpanningO365\3.5.0.0\Private\Invoke-SpanningRequest.ps1:108 char:50
+ ...         $response = Invoke-WebRequest -uri $response.nextLink -Header ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-WebRequest], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by mmatturro** [comment]
@MGrnovic it looks like the endpoint has changed from /users to /external/users. updating to the latest version seems to resolve this. There's still the 504 issue that I've run into with that endpoint, but this one seems resolved with the newest release.

**Comment by SPMatthewMcD** [comment]
Sorry for the delay. Yes, we changed the endpoint address and revved the Module to account for the update. I think that was your initial issue. I am going to close this one and track the 504s on the other issue thread.
