### ISSUE TITLE
Not listing "isDeleted" users

### ISSUE THREAD

**Issue by Csabulator** [SpanningCloudApps/SB365-Powershell#48]
Hey,

First off, I'd like to thank you for this tool, which comes handy in my automation! Big up!

My problem is that from today, neither Get-SpanningUser, nor Get-SpanningUsers gives back the users who has "isDeleted" attribute set to $true. If I'm explicitly search for that user with the Get-SpanningUser -UserPrincipalName xyz@domain.com it gives me back the attribute.

Here's the code example: Get-SpanningUsers | Where-Object { ($_.Assigned -eq $true) -and ($_.isDeleted -eq $true) }

Kinda bummer if I want to manage deleted, but license assigned users.

**Comment by SPMatthewMcD** [comment]
@Csabulator That should be working, so give me a bit to see if I somehow caused a regression. Can you follow up with me via email? matt.mcdermott@spanning.com I may need some additional info from you.

**Comment by SPMatthewMcD** [comment]
@Csabulator When I run:
`Get-SpanningUsers | Where-Object {($_.assigned -eq $true) -and ($_.isDeleted -eq $true)}`
I get the one licensed and deleted user in my tenant. 

You could also use:
`Get-SpanningUser -UserType Deleted | Where-Object {($_.assigned -eq $true)} `

There isn't much difference between the two.

If neither of these work for you please email me and we'll figure it out.

**Comment by Csabulator** [comment]
@SPMatthewMcD 
I tried both and it works now. Don't know what could be the issue, I tried to run my script with new powershell sessions, etc., but did not work. Now it works, thanks for the info, now I can finish the licensing script. :)

PS: I noticed that the underscore is missing from my lines, when I pasted it here. Strange, but that's definitely a typo there.

**Comment by SPMatthewMcD** [comment]
@Csabulator Excellent. I updated your comment above and added code ticks, that now shows your underscores (they were causing the italics without the tick).

Glad it's working, let me know if there is anything else.
