### ISSUE TITLE
List of users whose backups failing with error code 10004

### ISSUE THREAD

**Issue by ssuryakant20** [SpanningCloudApps/SB365-Powershell#53]
Is there any PowerShell command or program to return list of users whose backups failing with error code 10004. Such list will help to disable active license to those users and re-use for other users programmatically.

**Comment by SPMatthewMcD** [comment]
@ssuryakant20 There isn't a command to get users by error code.

You could use one of the code samples to query Azure AD and determine of the user has been disabled/removed/delicensed and then remove the license from the Spanning User through the API.

Please note that 30 days after you remove the Spanning License the users' backups will be deleted.

**Comment by ssuryakant20** [comment]
Got you , wish there could have been a command for that. No problem Thanks Mat,
