### ISSUE TITLE
SB365-Powershell command is not giving output as stated in usage examples.

### ISSUE THREAD

**Issue by ssuryakant20** [SpanningCloudApps/SB365-Powershell#59]
As mentioned below, this particular command is not giving output as stated below, instead it is giving output in the format mentioned in "Actual Output"

Enable-SpanningUsersFromCSVAdvanced -Path "C:\Test\Users.csv" -UpnColumn 1
The result should be displayed as follows:

Expected Output:
userPrincipalName          licensed
-------------------------  --------
willa@doghousetoys.com     True
kobe@doghousetoys.com      True
jazzy@doghousetoys.com     True
cheyenne@doghousetoys.com  True

Actual Output:
userPrincipalNames                                                                                                        licensed
------------------                                                                                                        --------
{willa@doghousetoys.com, kobe@doghousetoys.com, jazzy@doghousetoys.com, cheyenne@doghousetoys.com...}     True

**Comment by SPMatthewMcD** [comment]
True, I'll have to update the documentation. 
The `Enable-SpanningUsersFromCSVAdvanced` cmdlet was updated to use the preferred approach to bulk licensing `Enable-SpanningUserList`. I recommend that you use that cmdlet instead.

The alternative is to pass one user at a time and get the individual success/failure for each user.

**Comment by SPMatthewMcD** [comment]
Documentation updated, thank you.
