### ISSUE TITLE
Unauthorized error

### ISSUE THREAD

**Issue by GitHubJens** [SpanningCloudApps/SB365-Powershell#63]
I'm following [the guide](https://spanning.wistia.com/medias/7j46uee1ko) on how to create a token, but the views doesn't look like they do in the video.
It seems to me that Kaseya acquired Spanning a while back and since then have migrated all of this into their own portal.

I have tried creating a token in Kaseya with REST API access:
![image](https://user-images.githubusercontent.com/30659197/177169645-225b5e71-0b59-4717-b1af-21d2cd459e87.png)

But when I try this token I get an unauthorized error:
![image](https://user-images.githubusercontent.com/30659197/177172055-3c138723-4065-4dc0-ae29-b3b761fba3c8.png)

Can you point me in the right direction?

**Comment by GitHubJens** [comment]
You can close this one. It works against our own tenant when creating the token via https://o365-eu.spanningbackup.com. I will contact support for info on how to create tokens for other customers.

**Comment by SPMatthewMcD** [comment]
Every tenant has to issue its own token for users in that tenant. You have to login to each tenant and generate the token from there. You can't use any other method. Login to your other tenants as an Admin (either Global or Spanning) and you can generate the token.

At this time, you cannot use the VSA/UniView SSO user to generate the token.

**Comment by GitHubJens** [comment]
Ah! Thanks for the info :)
________________________________
Från: Matthew McDermott ***@***.***>
Skickat: Monday, July 4, 2022 11:49:16 PM
Till: SpanningCloudApps/SB365-Powershell ***@***.***>
Kopia: Jens Andersson ***@***.***>; State change ***@***.***>
Ämne: Re: [SpanningCloudApps/SB365-Powershell] Unauthorized error (Issue #63)


Every tenant has to issue its own token for users in that tenant. You have to login to each tenant and generate the token from there. You can't use any other method. Login to your other tenants as an Admin (either Global or Spanning) and you can generate the token.

At this time, you cannot use the VSA/UniView SSO user to generate the token.

**Comment by SPMatthewMcD** [comment]
Let me know when you have success and we can close. Else let me know if you have issues and I'll help.
