### ISSUE TITLE
All Users Report

### ISSUE THREAD

**Issue by mbianchisuncor** [SpanningCloudApps/SB365-Powershell#65]
I am trying to generate a list of all users in the tenant so I can see which ones are licensed/unlicensed.
We have around 96,000 users and 41,000 of them are licensed (according to the admin portal)
However when I run the PowerShell and export to csv I only get a list of around 32,000 users and 14,000 of them licensed.
I do notice that is seems to grab all users alphabetically A-J and then seems to only grab around 20-30 of the rest.

Any help would be greatly appreciated. Thanks.

**Comment by SPMatthewMcD** [comment]
Be sure to download the latest version of the Module. https://github.com/SpanningCloudApps/SB365-Powershell/releases/

To get the list of all users you can use the `Get-SpanningUser` cmdlet. If you put this into a variable like:
```
$users = Get-SpanningUser -UserType All
```
You can then filter the resulting list or export the list to CSV to determine who is licensed.
https://github.com/SpanningCloudApps/SB365-Powershell/blob/master/samples.md#export-unlicensed-users-to-csv

If you want to share your script with me you can do so here or via email at matt.mcdermott@spanning.com. (Please do not share your API key here!)

**Comment by mbianchisuncor** [comment]
That is basically what I ran just without the variable.

I have tried it both of these ways now:


  1.  Get-SpanningUser -UserType All | export-csv -Path C:\temp\Spanning\Licenses.csv


  1.  $users = Get-SpanningUser -UserType All
$users | export-csv -Path C:\temp\Spanning\Licenses.csv

In both cases it exports the data I want, it just doesn't get me all of the users, seems to stop early.

I just ran that second this morning and it only exported around 4500 users.

Thanks,

Michael Bianchi
Digital Delivery Analyst
Digital Experience & Communications Platforms
Suncor Energy Services Inc.
Suncor Energy Centre West Tower, 150 - 6th Ave SW
O: (403) 296-5248
E: ***@***.******@***.***>

**Comment by SPMatthewMcD** [comment]
We determined that there was a synchronization and communication issue with the Azure AD tenant service. I think we've resolved the issue.

I'll keep this issue open until you confirm that it's working for you.

**Comment by SPMatthewMcD** [comment]
@mbianchisuncor Closing this ticket as resolved. Please reopen if this is incorrect.
