### ISSUE TITLE
Extract users deleted one year ago or users with their last backup is a year old. Also to find users deleted from Microsoft

### ISSUE THREAD

**Issue by ssuryakant20** [SpanningCloudApps/SB365-Powershell#68]
How to find users deleted one year ago or users with their last backup is a year old. Also is there any way to find out list of users with below information with tag as "Deleted from Microsoft"

![image](https://github.com/SpanningCloudApps/SB365-Powershell/assets/63157726/32a00f07-5a43-45c5-aaf9-8b8d01eb3c3f)

**Comment by SPMatthewMcD** [comment]
You can use the `Get-SpanningUser -UserType Deleted` for users that have been deleted from Azure AD. There is no way that I know to find users with a year old backup.

[Get-SpanningUser](https://github.com/SpanningCloudApps/SB365-Powershell/blob/master/docs/Get-SpanningUser.md)
