### ISSUE TITLE
Need Help with some script for the Spanning PowerShell module please

### ISSUE THREAD

**Issue by iceo0orokz** [SpanningCloudApps/SB365-Powershell#70]
Can you please provide the PowerShell script that then would accurately list all user names,  email addresses, tags(such as archive read-only or deleted from Microsoft), and license types for any user who has an active license or an archive license? 🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by iceo0orokz** [comment]
Hi, following up on this.

**Comment by SPMatthewMcD** [comment]
You can use the `Get-SpanningUser` cmdlet to retrieve user information. The result contains the following info that should answer your question. [Get-SpanningUser documentation](https://github.com/SpanningCloudApps/SB365-Powershell/blob/master/docs/Get-SpanningUser.md)
```text
userPrincipalName : Scott@pinkstonfarms.com
email             : Scott@pinkstonfarms.com
displayName       : John
msId              : e7cfea61-dde5-43b4-9a19-a9299f18fe32
assigned          : True
isAdmin           : False
isDeleted         : False
isArchive         : False
```
