### ISSUE TITLE
compare permissions of two accounts

### ISSUE THREAD

**Issue by iceo0orokz** [SpanningCloudApps/SB365-Powershell#71]
Hi Team,

I need help to find the difference in access on the below two accounts on spanning. I'm scripting using powershell and trying to connect to spanning using a token and an email address.

It works with account

adm.himanshu.verma@1111systems.com 

![image](https://github.com/SpanningCloudApps/SB365-Powershell/assets/145169111/02bf1115-d0ae-4ac6-b773-48c8b02b34ee)

however gives below error while is use - svc.ps-scritping@1111systemscom.onmicrosoft.com

![image](https://github.com/SpanningCloudApps/SB365-Powershell/assets/145169111/65d87663-d425-4d10-9518-ed7ca88a0302)

Thank you,

**Comment by SPMatthewMcD** [comment]
Did you generate the API Key for each account separately? You cannot share a key.

**Comment by SPMatthewMcD** [comment]
Closing for lack of feedback.
