### ISSUE TITLE
How to assign Archive licenses to users

### ISSUE THREAD

**Issue by iceo0orokz** [SpanningCloudApps/SB365-Powershell#74]
Hello, 

I can't seem to find the examples to assign and unassign an Archive license to a user. Only see for standard licenses.

Please help.

**Comment by SPMatthewMcD** [comment]
There isn't an example yet. 
You can use the PowerShell IntelliSense on `Enable-SpanningUserList` to get the `-LicenseType` parameter and pick from the validation set `STANDARD` or `ARCHIVE`.

**Comment by iceo0orokz** [comment]
thank you!
