### ISSUE TITLE
Stopped backup on All SharePoint Sites

### ISSUE THREAD

**Issue by pintasingh** [SpanningCloudApps/SB365-Powershell#76]
Hi
To resolve SharePoint backup issue with throttle, want to stop spanning backup for all sharepoint sites. How can I do this using PowerShell command? Can somebody help?
Thanks!
P

**Comment by SPMatthewMcD** [comment]
The API does not currently support management of SharePoint Sites.

**Comment by pintasingh** [comment]
Thanks for quick reply!!
So, what is the other way to stop backup for all SharePoint sites?

**Comment by SPMatthewMcD** [comment]
Contact Support and they can review the issues and offer support. They are available via email at support@spanning.com or Chat at https://helpdesk.kaseya.com/hc/en-gb/categories/4405748082833

**Comment by SPMatthewMcD** [comment]
Closing for now, please reopen if you have additional questions.
