### ISSUE TITLE
Archive Spanning license via PowerShell.

### ISSUE THREAD

**Issue by iceo0orokz** [SpanningCloudApps/SB365-Powershell#77]
please forward me the steps or article on how to move bulk users from Standard to Archive Spanning license via PowerShell.

**Comment by SPMatthewMcD** [comment]
You can use a version of the sample [License Users with an Office 365 License](https://github.com/SpanningCloudApps/SB365-Powershell/blob/master/sample-license-users.md) to perform this action. When you get to the licensing step use the `-LicenseType` parameter to specify `ARCHIVE`.

**Comment by iceo0orokz** [comment]
got it thank you... am I able to add users in bulk to those scripts or would i need to perform it individually

**Comment by SPMatthewMcD** [comment]
I believe you can do it in bulk with `Enable-SpanningUserList`.

**Comment by SPMatthewMcD** [comment]
Closing as answered, reopen if necessary.
