### ISSUE TITLE
Any Powershell commands to assign/unassign specific to archive licenses ?

### ISSUE THREAD

**Issue by ssuryakant20** [SpanningCloudApps/SB365-Powershell#78]
Recently we have started using archive licenses for deleted users in M365. Does the new releases of Powershel Modules has any commands to operate or assign/unassign archive licenses to Spanning users ?

**Comment by SPMatthewMcD** [comment]
`Enable-SpanningUserList` takes a `-LicenseType` parameter of STANDARD or ARCHIVE.
