### ISSUE TITLE
v3.3 fails to get imported to Azure Automation Account + fixes

### ISSUE THREAD

**Issue by o-l-a-v** [SpanningCloudApps/SB365-Powershell#9]
v3.3 release fails to import to Azure Automation Account.

First thing I think is related is in the psd1 file, where you have capped the version number to two numbers. I changed it from 3.3 to 3.3.0.0

Second thing I think is and improvement, it using "Import-Module" instead of dot sourcing when importing the modules in the psm1 file.

Third thing is that Automation Account recommends modules folder structure to be `<NameOfModule>\<Version>\<stuff>`. So `SpanningO365\3.3.0.0\<stuff>`.

I tried to clone your repo so I could commit changes (I'm no GitHub pro, I probably did this the wrong way), so I'll just attach the ZIP with working changes that made me able to import it to Azure Automation Account. Please include in future releases.

[SpanningO365.zip](https://github.com/SpanningCloudApps/SB365-Powershell/files/3252031/SpanningO365.zip)

**Comment by SPMatthewMcD** [comment]
Thanks, I'll have a look.

**Comment by SPMatthewMcD** [comment]
I finally got around to implementing the Connection parameter and rearranging the Release file for Azure Automation. I think I'll create a `build1 script for the ZIP format that Azure prefers, but I might bite the bullet and reorganize the whole project. I hope this build addresses your issues.
